name: chai_interactions
description: "Some interaction designs for CHAI"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tilt: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  palette_generator: ^0.3.3+3
  mesh_gradient: ^1.3.7
  smooth_sheets: ^0.10.2
  gaimon: ^1.3.0
  flutter_markdown: ^0.7.3+2
  provider: ^6.1.2
  jovial_svg: ^1.1.24


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^6.3.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.9
  dependency_validator:
  build_runner: ^2.3.3
  freezed: ^2.4.2
  json_serializable: ^6.6.1
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/haptics/

  fonts:
    - family: HgiStrokeRounded
      fonts:
        - asset: assets/fonts/hgi-stroke-rounded.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/InterVariable.ttf
        - asset: assets/fonts/inter/InterVariable-Italic.ttf
          style: italic
    - family: PP Neue Machina
      fonts:
        - asset: assets/fonts/pp-neue-machina/PPNeueMachina-Light.otf
          weight: 300
        - asset: assets/fonts/pp-neue-machina/PPNeueMachina-Regular.otf
          weight: 400
        - asset: assets/fonts/pp-neue-machina/PPNeueMachina-Ultrabold.otf
          weight: 800
    - family: Silkscreen
      fonts:
        - asset: assets/fonts/silkscreen/Silkscreen-Regular.ttf
          weight: 400
        - asset: assets/fonts/silkscreen/Silkscreen-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: false
  ios: true
  image_path: assets/logos/chai-logo-light.jpeg
  image_path_ios_dark_transparent: assets/logos/chai-logo-dark.png
  remove_alpha_ios: true
  web:
    generate: false
  macos:
    generate: false
  windows:
    generate: false
  linux:
    generate: false

flutter_native_splash:
  color: "#F4F4F4"
  image: assets/logos/chai-text-logo.png
  ios_content_mode: center
