name: chai_interactions
description: "Some interaction designs for CHAI"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tilt: ^2.3.0
  flutter_staggered_animations: ^1.1.1
  palette_generator: ^0.3.3+3
  mesh_gradient: ^1.3.7
  smooth_sheets: ^0.9.2
  gaimon: ^1.3.0
  flutter_markdown: ^0.7.3+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  analyzer: ^6.3.0
  firebase_core_platform_interface: ^5.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.9
  dependency_validator:
  build_runner: ^2.3.3
  freezed: ^2.4.2
  json_serializable: ^6.6.1
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/chai-logo-light.jpeg"
  image_path_ios_dark_transparent: "assets/chai-logo-dark.png"
  remove_alpha_ios: true
  web:
    generate: false
  macos:
    generate: false
  windows:
    generate: false
  linux:
    generate: false

flutter_native_splash:
  color: "#F4F4F4"
  image: assets/chai-text-logo.png
  ios_content_mode: center
